### ISSUE TITLE
[Suggestion] Add Spotify Support

### ISSUE THREAD

**Issue by getxd-dev** [Garlic-Team/MusicBot#9]
title says it all.

**Comment by xhyrom** [comment]
I'm working on a complete rewrite, which is in the 'dev' branch so I'll definitely add it there.

**Comment by xhyrom** [comment]
https://github.com/Garlic-Team/MusicBot/tree/dev

**Comment by xhyrom** [comment]
https://github.com/Garlic-Team/MusicBot/commit/bc7660a48e3508f6617f72669ca9c0c2dac0c368
